# Generated by Django 2.1 on 2018-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('file_path', models.CharField(max_length=2000)),
                ('file_name', models.CharField(max_length=2000)),
                ('file_real_name', models.CharField(max_length=2000)),
            ],
        ),
    ]
